config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  root 'static_pages#home'
  get 'static_pages/home'
  get 'address' => 'address#index'
  post 'address' => 'address#create'
  post 'login'   => 'session#create'
  get 'logout' => 'session#destroy'


end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
   validates :name,  presence: true, length: { maximum: 50 }
   validates :email,  presence: true, length: { maximum: 50 }
   validates :business_phone,  presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :addres , dependent: :destroy
  before_save   :downcase_username, :downcase_password
  validates :username,  presence: true, length: { maximum: 20 }
  validates :password,  presence: true, length: { maximum: 20 }
  has_secure_password
  
  private
  
    # Converts email to all lower-case.
    def downcase_username
      self.username = username.downcase
    end
    
    def downcase_password
      self.password = password.downcase
    end
    
  
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
  before_action :logged_in_user
  
  def index
    @user_id = current_user.id
    @Address = Address.all
  end
  
  def new
    @address = Address.new
  end
  
  
  def create
    @address_param = params[:address]
    @address = Address.new(address_params)
    p "-------------"
    p @address
    
    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'User was successfully created.' }
      else
        format.html { render :bong }
      end
    end

  end
  
  private 
  
    def address_params
      params.require(:address).permit(:user_id, :name, :email, :business_phone, :home_phone, :business_address, :home_address, :notes)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def create
    user = User.find_by(username: params[:session][:username].downcase)
 
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to(:address)
    else
      # Create an error message.
      flash[:notice] = 'Invalid username/password combination' # Not quite right!
      redirect_to(:back)
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
  
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/address_book_helper.rb
module AddressBookHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Address Book"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
  
end

app/helpers/session_helper.rb
module SessionHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user
        log_in user
        @current_user = user
      end
    end
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to root_url
    end
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/address/_dialog.html.erb
 <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add Contact</h4>
        </div>
        <div class="modal-body">
           <%= render 'form' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

app/views/address/_form.html.erb
<div class="well">
      <%# form_for(:address, url: address_path, remote: true) do |f| %>
       <%= form_for(:address, url: address_path) do |f| %>
        <%= f.text_field :name, class: 'form-control', :placeholder => "name (required)", "required"=>"true"  %>
        <%= f.text_field :email, class: 'form-control', :placeholder => "email (required)", "required"=>"true" %>
        <%= f.text_field :business_phone, class: 'form-control', :placeholder => "business phone (required)", "required"=>"true" %>
        <%= f.text_field :home_phone, class: 'form-control', :placeholder => "home phone" %>
        <%= f.text_area :business_address, class: 'form-control', :placeholder => "business address" %>
        <%= f.text_area :home_address, class: 'form-control', :placeholder => "home address" %>
        <%= f.text_area :notes, class: 'form-control', :placeholder => "notes" %>
        <%= f.hidden_field :user_id, class: 'form-control', value: @user_id %>
      
  
        <%= f.submit "save", class: "btn btn-primary" %>
      <% end %>
</div>

app/views/address/_order.html.erb
<div class="well">
           <a class="btn btn-default" href="#" role="button">ALL</a>
            <%('A'..'Z').each { |letter| %>
              <a class="btn btn-default" href="#" role="button"><%= letter%></a>  
            <%}%>
        </div>

app/views/address/_search.html.erb
<div class="well">
            <input type="text" class="form-control" id="search-contact" placeholder="Search Contact">
            <button type="submit" class="btn btn-default">Search</button>
        </div>

app/views/address/bong.html.erb
<h1>Temporary rendered view</h1>
<br/>
<br/>
<%= @address_param %>

app/views/address/index.html.erb
  <div class="container-fluid">

    <div class="row container-contact">
      <div class="col-md-2 well" id="add-contact">
        <h3>My Contact</h3>
            <% # link_to "Add Contact", address_path, class: "btn btn-primary", "data-toggle"=>"modal" %>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add Contact</button>
      </div>
      
      <div class="col-md-6">
        
        <%= render 'search' %>
        <%= render 'order' %>

        <div class="well white contact-block">
          <ul class="contacts">
               <li>
                 Alexander Otsuka
               </li>
               
                <li>
                 Anita Yung
               </li>
          </ul>
        </div>
      </div>
      
      <div class="col-md-4 well">
        <h3>Contact Preview</h3>
      </div>
    </div>
  </div>
  
  
  <%= render 'dialog' %>

app/views/address/new.js.erb
// Add the dialog title
// $('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Add New Customer");
 
// // Render the new form
// $('.modal-body').html('<%= j render("form") %>');
 
// // Show the dynamic dialog
// $('#dialog').modal("show");
 
// // Set focus to the first element
// $('#dialog').on('shown.bs.modal', function () {
// 	  $('.first_input').focus()
// })

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="container">
  <small>
    The <a href="http://www.twitter.com/">Address Book</a>
    by <a href="http://www.facebook.com/">Bima Ngganteng</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   root_path %></li>
      <li><%= link_to "Contact", root_path %></li>
      <li><a href="http://engadget.com/">News</a></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Address Book", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></strong></li>
        <% if logged_in? %>
          <li><%= link_to "Address",    address_path %></strong></li>
          <li><%= link_to "User",    users_path %></strong></li>
          <li><%= link_to "Logout",    logout_path %></strong></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

        <%= render partial: "shared/flash_messages", flash: flash %> 

      <%= yield %>
      
    </div>
    <div>
      <%= render 'layouts/footer' %>
      <% #debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<script type="text/javascript">
    window.location.href="/address"  // put your correct path in a string here
  </script>
<% end %>


<div class="center vertical-center">
  <% if !logged_in? %>
        <h1>Welcome ;)</h1>
        <br/>

        <br/>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="well">
            <%= form_for(:session, url: login_path) do |f| %>
      
              <%= f.text_field :username, class: 'form-control', :placeholder => "username" %>
      
              <%= f.password_field :password, class: 'form-control', :placeholder => "password" %>
            
        
              <%= f.submit "Log in", class: "btn btn-primary" %>
            <% end %>
            </div>
          </div>
        </div>
    <% else %>
      <h3>What are you looking at?? ;)</h3>
    <% end %>

</div>

app/views/users/_form.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well">

            <%= form_for(@user) do |f| %>
                <% if @user.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
              
                    <ul>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
            
            
                <%= f.text_field :username , class: 'form-control', :placeholder => "username"%>
                <%= f.text_field :password , class: 'form-control', :placeholder => "password" %>
                <%= f.submit "Save", class: "btn btn-primary" %>
            <% end %>
          
          </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
    <div class="row container-contact">

          <h1>Editing User</h1>
          <%= render 'form' %>
          <%= link_to 'Back', users_path, :class=>"btn btn-warning btn-sm", :role=>"button"  %>
          
    </div>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
    <div class="row container-contact">

            <div class="col-md-2 well">
              <h3>Listing Users</h3>
               <!--<button class="btn btn-primary" type="submit">Add User</button>-->
                <%= link_to 'New User', new_user_path, :class=>"btn btn-primary", :role=>"button" %>
            </div>
            
            <div class="col-md-6">
          
              <div class="well white user-block">
                <ul class="contacts">
                    <li>
                      <span class="span-user text-info"><h4>Username</h4></span>
                      <span class="span-password text-info"><h4>Password</h4></span>
                      <span class="span-tombol text-info" style="margin-left:25px;"><h4>Command</h4></span>
                    </li>
                    <% @users.each do |user| %>
                      <li>
                          <span class="span-user text-info"><strong><%= user.username %></strong></span>
                          <span class="span-password text-info" style="overflow:hidden"><strong><%= user.password_digest %></strong></span>
                          <span class="span-tombol text-info" style="margin-left:25px;">
                            <% #link_to 'Show', user, :class=>"btn btn-default btn-sm", :role=>"button" %>
                            <%= link_to 'Edit', edit_user_path(user), :class=>"btn btn-default btn-sm", :role=>"button" %>
                            <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-default btn-sm", :role=>"button" %>
                          </span>
                      </li>
                    <% end %>
                </ul>
              </div>
            </div>

  </div>
</div>




  
  
  

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container-fluid">
    <div class="row container-contact">

          <div id="notice" class="alert alert-danger">
            <strong></strong>Warning!zzzzz</strong> <%= notice %>
          </div>
          
          <p>
            <strong>Username:</strong>
            <%= @user.username %>
          </p>
          
          <p>
            <strong>Password:</strong>
            <%= @user.password %>
          </p>
          
          <%= link_to 'Edit', edit_user_path(@user) %> |
          <%= link_to 'Back', users_path %>
          
          
    </div>
</div>